### PR TITLE
Changed template to interate over the model

### PR DESCRIPTION
**Pull request by ilcrawford**

### CODE REVIEW

**Comment by ScriptGadget** [comment]
I'll be able to review this in the morning. @jamesleebaker  are you cool with me working pull requests?

**Comment by glorioustephan** [comment]
Yes, feel free!

**Comment by ScriptGadget** [comment]
Pulled it down and merged it locally and it looks good. Thanks, Iman!

**Comment by ilcrawford** [comment]
I have a few more. Learning the framework.

**Pull request merged**
